name: Stonewood DesignLab
favicon: null
layout_spectrum: 0.00762
typography_spectrum: 0.7484
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f9f9f9'
    - '#1d1d1b'
    - '#adadad'
    - '#535351'
    - '#dddddd'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose:
  - name: follow
    item: null
    url: null
