name: Stonewood DesignLab
favicon: null
layout_spectrum: 0.23018
typography_spectrum: 0.7484
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#223e7d'
    - '#ffffff'
    - '#919193'
    - '#e71f25'
    - '#ffee00'
  brandStrength: 1
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose:
  - name: follow
    item: null
    url: null
